# This file is ONLY used for creating a docker image to host my personal
# blog. The gem packages and dependencies may not work for other jekyll blogs.
#
# If you want to create a jekyll image for your jekyll static website,
# you can customize this file as you want.
#
# Roadmap:
# 2015-03-29: upgrade jekyll to 3.0 and use rouge instead of pygments
#
FROM centos:7

MAINTAINER Conghui He <heconghui@gmail.com> version: 2.0

#RUN yum update -y && yum clean all
RUN yum install -y openmpi
