import os
Import('*')

lib = "mdlib"
# these modules will compiled in to library
lib_modules = """
			  fd4t10s-damp-zjh.c
			  fd4t10s-zjh.c
              """.split()

extra_include_dir = [
]

############################### for library ###########################
#######################################################################
# clone the environment from global env and make some modification of it
new_c_compiler = c_compiler
# if compiler_set == 'sw':
  # new_c_compiler = ['swacc']
# else:
  # new_c_compiler = c_compiler

myenv    = env.Clone(
    CC = new_c_compiler,
    CPPPATH = extra_include_dir)

# compile to object files
lib_objs = myenv.StaticObject(lib_modules)

# compile library
lib_ar   = myenv.StaticLibrary(target = lib, source = lib_objs)

# install
myenv.Install("#" + dirs['lib'], lib_ar)
