import os

libs = ['pthread']

env = Environment(
    LIBS = libs,
    CXXFLAGS = ['-g', '-O0'],
    ENV = os.environ)

hello = env.Program('hello', 'hello.cpp')

run = env.Command('hello.log', hello, './hello')
Depends(run, hello)

# AlwaysBuild(run)
# env.Alias('run', hello, hello[0].abspath)

