# vim: fdm=marker fdl=0

from rsf.proj import *
import os
from os import system

def mkdir(path):#{{{
  if not os.path.exists(path):
    os.makedirs(path)
#}}}
def plot(file, title):#{{{
  Plot(file, '''
    grey title="%s" color=j allpos=y pclip=100 bias=1500 gainpanel=1
    scalebar=y barreverse=y barunit=m/s barlabel=Velocity''' % title)
#}}}

# marmvel.hh contains Marmousi model which can be downloaded from the server using Fetch.
#Fetch('marmvel.hh','marm')
Fetch('marmvel.hh', 'marm', server = 'local', top = os.environ['HOME'] + '/data/')

Flow('vel','marmvel.hh',
  '''
  dd form=native |
  window j1=5 j2=5 |
  put label1=Depth  unit1=m label2=Lateral unit2=m
  ''')

Flow('smvel','vel','smooth rect1=25 rect2=60')
plot('vel', 'Marmousi model')
plot('smvel', 'Smoothed model')
Result('marm', 'vel smvel', 'OverUnderAniso')

datapath = './rsfdata/'
checkpointdir='./checkpoingdir/'
os.environ['DATAPATH'] = datapath
os.environ['CHECKPOINTDIR'] = checkpointdir
#os.environ['OMP_NUM_THREADS'] = '2'
mkdir(datapath)
mkdir(checkpointdir)

task = ARGUMENTS.get('task')
if task == 'fm':
  system('''./fm-damp vinit=vel.rsf shots=shots.rsf
  fm=10 amp=1 dt=0.0015 ns=40 ng=461 nt=2000 nb=30
  sxbeg=0 szbeg=6 jsx=10 jsz=0 gxbeg=0 gzbeg=6 jgx=1 jgz=0
  '''.replace('\n', ' '))
elif task == 'essfwi':
  system('''./essfwi vin=smvel.rsf  shots=shots.rsf
  grads=grads.rsf objs=objs.rsf illums=illums.rsf
  niter=300 nb=30 vout=vsnaps.rsf
  '''.replace('\n', ''))


#Flow('shots','vel',
  #'''
  #../../../bin/fm-damp vinit=${SOURCES[0]} shots=${TARGETS[0]}
  #fm=10 amp=1 dt=0.0015 ns=40 ng=461 nt=2000 nb=30
  #sxbeg=0 szbeg=6 jsx=10 jsz=0 gxbeg=0 gzbeg=6 jgx=1 jgz=0
  #''', stdin=0, stdout=-1)
#Plot('shots','grey color=g title=shot label2= unit2=',view=1)


#Plot('shot4','shots','window n3=1 f3=4| grey color=g title=shot4 label2=Lateral unit2=m')
#Plot('shot11','shots','window n3=1 f3=11| grey color=g title=shot11 label2=Lateral unit2=m')
#Plot('shot17','shots','window n3=1 f3=17| grey color=g title=shot17 label2=Lateral unit2=m')
#Result('shotsnap','shot4 shot11 shot17','SideBySideAniso',vppen='txscale=2.')

## smoothed velocity model
#Flow('smvel','vel','smooth repeat=10 rect1=10 rect2=20')
#Plot('smvel',
     #'''
     #grey title="Smoothed Marmousi model" wantitle=y allpos=y color=j
     #pclip=100 scalebar=y bartype=v barlabel="V" barunit="m/s"
  #screenratio=0.45 color=j labelsz=10 titlesz=12
     #''' )

#Result('marm','vel smvel','TwoRows')

## use the over-smoothed model as initial model for FWI
##Flow('vsnaps grads objs illums','smvel shots',
  ##'''
  ##sffwi2d shots=${SOURCES[1]} grads=${TARGETS[1]} objs=${TARGETS[2]}
  ##illums=${TARGETS[3]} niter=300 precon=y
  ##''')
##Result('vsnaps',
  ##'''
  ##grey title="Updated velocity" allpos=y color=j pclip=100
  ##scalebar=y bartype=v barlabel="V" barunit="m/s"
  ##''')
##Plot('vsnap1','vsnaps',
  ##'''
  ##window n3=1|grey title="Updated velocity, iter=1" allpos=y color=j pclip=100
  ##scalebar=y bartype=v barlabel="V" barunit="m/s" labelsz=10 titlesz=12
  ##''')
##Plot('vsnap20','vsnaps',
  ##'''
  ##window n3=1 f3=19|grey title="Updated velocity, iter=20" allpos=y color=j pclip=100
  ##scalebar=y bartype=v barlabel="V" barunit="m/s" labelsz=10 titlesz=12
  ##''')
##Plot('vsnap50','vsnaps',
  ##'''
  ##window n3=1 f3=49|grey title="Updated velocity, iter=50" allpos=y color=j pclip=100
  ##scalebar=y bartype=v barlabel="V" barunit="m/s" labelsz=10 titlesz=12
  ##''')

##Plot('vsnap100','vsnaps',
  ##'''
  ##window n3=1 f3=99|grey title="Updated velocity, iter=100" allpos=y color=j pclip=100
  ##scalebar=y bartype=v barlabel="V" barunit="m/s" labelsz=10 titlesz=12
  ##''')
##Plot('vsnap180','vsnaps',
  ##'''
  ##window n3=1 f3=179|grey title="Updated velocity, iter=180" allpos=y color=j pclip=100
  ##scalebar=y bartype=v barlabel="V" barunit="m/s" labelsz=10 titlesz=12
  ##''')
##Plot('vsnap300','vsnaps',
  ##'''
  ##window n3=1 f3=299|grey title="Updated velocity, iter=300" allpos=y color=j pclip=100
  ##scalebar=y bartype=v barlabel="V" barunit="m/s" labelsz=10 titlesz=12
  ##''')

##Result('vsnap','vsnap1 vsnap20 vsnap50 vsnap100 vsnap180 vsnap300','TwoRows')

###########################################################################
###Plot('vsnapa','vsnap1 vsnap100','OverUnderAniso',vppen='txscale=2')
###Plot('vsnapb','vsnap20 vsnap180','OverUnderAniso',vppen='txscale=2')
###Plot('vsnapc','vsnap50 vsnap300','OverUnderAniso',vppen='txscale=2')
###Result('vsnap','vsnapa vsnapb vsnapc','SideBySideAniso',vppen='txscale=1.')

##Result('grads','grey title="Updated gradient" scalebar=y color=j ')
##Result('illums','grey title="illumination" scalebar=y color=j')

##Result('objs',
  ##'''
  ##sfput n2=1 label1=Iteration unit1= unit2= label2= |
  ##graph title="Misfit function" dash=0 plotfat=5  grid=y yreverse=n
  ##''')


End()
