import os
Import('*')

lib = 'rsf'
# these modules will compiled in to library
lib_modules = """
alloc.c
c99.c
error.c
file.c
getpar.c
kiss_fft.c
komplex.c
simtab.c
              """.split()

############################### for library ###########################
if compiler_set == 'sw':
  cflags = ['-O0']
else:
  cflags = ['-O2']

myenv    = Environment(CC = c_compiler,
                       CFLAGS = cflags,
                       ENV = os.environ)

# compile to object files
lib_objs = myenv.StaticObject(lib_modules)

# compile library
lib_ar   = myenv.StaticLibrary(target = lib, source = lib_objs)

# install
myenv.Install("#" + dirs['lib'], lib_ar)
