import os
Import('*')

lib = "common"
# these modules will compiled in to library
lib_modules = """
			  common.cpp
			  ricker-wavelet.cpp
              """.split()

extra_include_dir = [
  os.environ['RSFROOT'] + '/include',
]

############################### for library ###########################
#######################################################################
# clone the environment from global env and make some modification of it
myenv    = env.Clone(CPPPATH = extra_include_dir)
myenv.Append(CXXFLAGS = '-DNO_BLAS')

# compile to object files
lib_objs = myenv.StaticObject(lib_modules)

# compile library
lib_ar   = myenv.StaticLibrary(target = lib, source = lib_objs)

# install
myenv.Install("#" + dirs['lib'], lib_ar)
